### ISSUE TITLE
config.php belongs to user root by default: Could not auto-encrypt passwords. Error was: "cannot write file".

### ISSUE THREAD

**Issue by MexHigh** [YOURLS/docker#151]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

#### The problem

I'm using the Yourls Docker Image with the following docker-compose file below. When entering the frontend at `https://yourls-url/admin/` the following warning is shown in a banner at the top:

`Could not auto-encrypt passwords. Error was: "cannot write file".`

#### Troubleshooting

As I've read in https://github.com/YOURLS/YOURLS/wiki/Username-Passwords, this is caused by missing write permissions for the www-data user. I built a custom Dockerfile for yourls to override its ENTRYPOINT and CMD to debug what happens in `docker-entrypoint.sh`. 

It just copies the files from `/usr/src/yourls/` to the current directory if there is nothing in it. Then it checks, if the file `user/config.php` exits. If not (which is the case for the docker container without a volume mount), then the `/usr/src/yourls/user/config-docker.php` is copied to that location. This causes the destination file (`user/config.php`) to belong to the root user (as he is executing the `docker-entrypoint.sh` file), **rendering the auto-encryption feature useless**.

This happens here: https://github.com/YOURLS/docker/blob/main/docker-entrypoint.sh#L75

If the `-a` or `--preserve=all` flag is added to the `cp` call, the destination file would also belong to `www-data`, which would fix this issue. Please let me know if I should open a MR on this. I don't know if this is intended, but it is kind of irritating to see this warning every week.

### Expectation

Login to the admin dashboard without any errors.

### Reproduction steps

1. Install yourls with the docker-compose file below (without volume mount to `/var/www/html/`)
2. Enter the admin frontend
3. See the warning

### Context

My docker-compose file:

```yaml
version: '3'
services:

  yourls:
    image: yourls:1.8.2
    container_name: yourls
    restart: always
    networks:
      db:
      # my database is in another docker network
      # but i have confirmed that this works as intended
    ports:
      - 8020:80
    # I only persist the plugins folder as everything else is configured by envvars
    volumes:
      - ./plugins:/var/www/html/user/plugins
    environment:
      YOURLS_SITE: <redacted>
      YOURLS_USER: leon
      YOURLS_PASS: ${YOURLS_PASS}
      YOURLS_DB_HOST: mysql.db
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: ${YOURLS_DB_PASS}
      YOURLS_DB_NAME: yourls
      YOURLS_PRIVATE: 'TRUE'

networks:
  db:
    external: true
```

My custom Dockerfile to test the `docker-entrypoint.sh` file:

```Dockerfile
FROM yourls:latest
CMD ["tail", "-f", "/dev/null"]
```
