### ISSUE TITLE
Volume in docker-compose.yml

### ISSUE THREAD

**Issue by talesam** [YOURLS/docker#202]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I created a docker-compose.yml based on yours which is available here: https://hub.docker.com/_/yourls
however, it does not have a volume, the data is stored in mysql, but because it does not have a permanent volume, because if you restart the container, you lose all information.

### Motivation

There is no persistent volume, if the containers are destroyed where will the data go?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @talesam.
Indeed, the example provided on Docker Hub documentation is without persistence.
You are free to make this example fit your needs.
To do so, I'd recommend the following materials:
* https://hub.docker.com/_/mysql
* https://docs.docker.com/compose/compose-file/

**Comment by talesam** [comment]
I managed to solve it, who wants to copy it, it's working very well.. I changed some things..

```
version: '3.9'

services:
  yourls-db:
    image: mariadb:latest
    container_name: yourls-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456root
      MYSQL_DATABASE: yourls
      MYSQL_USER: yourls
      MYSQL_PASSWORD: 123456
    volumes:
      - ./Yourls/db:/var/lib/mysql
    networks:
      yourls-net:

  yourls:
    image: yourls:latest
    container_name: yourls
    restart: always
    expose:
      - 80
    environment:
      YOURLS_DB_HOST: yourls-db:3306
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: 123456
      YOURLS_DB_NAME: yourls
      YOURLS_SITE: https://your-domain
      YOURLS_USER: admin
      YOURLS_PASS: 1234
    depends_on:
      - yourls-db
    networks:
      yourls-net:

networks:
  yourls-net:
      name: yourls-net
```
